include:
  - project: 'cicd/gitlab-templates'
    ref: main
    file: 'node.gitlab-ci.template.yml'

variables:
  BUILD_PROJECT: 'yes'
  PUSH_GITHUB: 'yes'
  GITHUB_MIRROR_URL: 'git@github.com:pimsdsigd/damntools-types.git'

Publish:
  needs:
    - Build
  dependencies:
    - Build
