include:
    -   project: 'cicd/gitlab-templates'
        ref: main
        file: 'node.gitlab-ci.template.yml'

variables:
    BUILD_PROJECT: 'yes'
    SONAR_SCANNER_FILE: sonar-scanner.js

Publish:
    needs:
        - Build
    dependencies:
        - Build

