import {ArrayList} from "./src"

console.log("{}", typeof {})
console.log("[]", typeof [])
console.log("ArrayList.empty()", typeof ArrayList.empty())
console.log("1", typeof 1)
console.log("0", typeof 0)
console.log("''", typeof "")
console.log("'true'", typeof "true")
console.log("true", typeof true)
console.log("false", typeof false)
console.log("null", typeof null)
console.log("undefined", typeof undefined)
console.log("undefined", typeof undefined)
expect()